// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kyt.proto

package kytpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	SourceAddress string                 `protobuf:"bytes,3,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	Chain         string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenRequest) Reset() {
	*x = ScreenRequest{}
	mi := &file_kyt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenRequest) ProtoMessage() {}

func (x *ScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenRequest.ProtoReflect.Descriptor instead.
func (*ScreenRequest) Descriptor() ([]byte, []int) {
	return file_kyt_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *ScreenRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ScreenRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *ScreenRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ScreenRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      string                 `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	RiskScore     int32                  `protobuf:"varint,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Exposure      string                 `protobuf:"bytes,3,opt,name=exposure,proto3" json:"exposure,omitempty"`
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	Vendor        string                 `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	CacheHit      bool                   `protobuf:"varint,6,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenResponse) Reset() {
	*x = ScreenResponse{}
	mi := &file_kyt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenResponse) ProtoMessage() {}

func (x *ScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenResponse.ProtoReflect.Descriptor instead.
func (*ScreenResponse) Descriptor() ([]byte, []int) {
	return file_kyt_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenResponse) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *ScreenResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *ScreenResponse) GetExposure() string {
	if x != nil {
		return x.Exposure
	}
	return ""
}

func (x *ScreenResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ScreenResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ScreenResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_kyt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_kyt_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScreenId      string                 `protobuf:"bytes,2,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,5,opt,name=chain,proto3" json:"chain,omitempty"`
	Exposure      string                 `protobuf:"bytes,6,opt,name=exposure,proto3" json:"exposure,omitempty"`
	Severity      string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Assignee      string                 `protobuf:"bytes,9,opt,name=assignee,proto3" json:"assignee,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,11,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_kyt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_kyt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_kyt_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

func (x *Alert) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Alert) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Alert) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Alert) GetExposure() string {
	if x != nil {
		return x.Exposure
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Alert) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Alert) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Alert) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

var File_kyt_proto protoreflect.FileDescriptor

const file_kyt_proto_rawDesc = "" +
	"\n" +
	"\tkyt.proto\x12\x03kyt\"\x93\x01\n" +
	"\rScreenRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12%\n" +
	"\x0esource_address\x18\x03 \x01(\tR\rsourceAddress\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"\xb9\x01\n" +
	"\x0eScreenResponse\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x05R\triskScore\x12\x1a\n" +
	"\bexposure\x18\x03 \x01(\tR\bexposure\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\x12\x16\n" +
	"\x06vendor\x18\x05 \x01(\tR\x06vendor\x12\x1b\n" +
	"\tcache_hit\x18\x06 \x01(\bR\bcacheHit\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tscreen_id\x18\x02 \x01(\tR\bscreenId\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x05 \x01(\tR\x05chain\x12\x1a\n" +
	"\bexposure\x18\x06 \x01(\tR\bexposure\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bassignee\x18\t \x01(\tR\bassignee\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tclosed_at\x18\v \x01(\tR\bclosedAt2m\n" +
	"\n" +
	"KYTService\x121\n" +
	"\x06Screen\x12\x12.kyt.ScreenRequest\x1a\x13.kyt.ScreenResponse\x12,\n" +
	"\bGetAlert\x12\x14.kyt.GetAlertRequest\x1a\n" +
	".kyt.AlertBAZ?github.com/ai-crypto-onramp/aml-kyt-screening/internal/pb;kytpbb\x06proto3"

var (
	file_kyt_proto_rawDescOnce sync.Once
	file_kyt_proto_rawDescData []byte
)

func file_kyt_proto_rawDescGZIP() []byte {
	file_kyt_proto_rawDescOnce.Do(func() {
		file_kyt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyt_proto_rawDesc), len(file_kyt_proto_rawDesc)))
	})
	return file_kyt_proto_rawDescData
}

var file_kyt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kyt_proto_goTypes = []any{
	(*ScreenRequest)(nil),   // 0: kyt.ScreenRequest
	(*ScreenResponse)(nil),  // 1: kyt.ScreenResponse
	(*GetAlertRequest)(nil), // 2: kyt.GetAlertRequest
	(*Alert)(nil),           // 3: kyt.Alert
}
var file_kyt_proto_depIdxs = []int32{
	0, // 0: kyt.KYTService.Screen:input_type -> kyt.ScreenRequest
	2, // 1: kyt.KYTService.GetAlert:input_type -> kyt.GetAlertRequest
	1, // 2: kyt.KYTService.Screen:output_type -> kyt.ScreenResponse
	3, // 3: kyt.KYTService.GetAlert:output_type -> kyt.Alert
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kyt_proto_init() }
func file_kyt_proto_init() {
	if File_kyt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyt_proto_rawDesc), len(file_kyt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyt_proto_goTypes,
		DependencyIndexes: file_kyt_proto_depIdxs,
		MessageInfos:      file_kyt_proto_msgTypes,
	}.Build()
	File_kyt_proto = out.File
	file_kyt_proto_goTypes = nil
	file_kyt_proto_depIdxs = nil
}
