// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kyt.proto

package kytpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KYTService_Screen_FullMethodName   = "/kyt.KYTService/Screen"
	KYTService_GetAlert_FullMethodName = "/kyt.KYTService/GetAlert"
)

// KYTServiceClient is the client API for KYTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KYTService is served by the AML / KYT Screening service for the
// Transaction Orchestrator on the synchronous transaction path.
type KYTServiceClient interface {
	// Screen runs a synchronous KYT screen for a destination address.
	Screen(ctx context.Context, in *ScreenRequest, opts ...grpc.CallOption) (*ScreenResponse, error)
	// GetAlert returns the alert with the given id (compliance dashboard).
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error)
}

type kYTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKYTServiceClient(cc grpc.ClientConnInterface) KYTServiceClient {
	return &kYTServiceClient{cc}
}

func (c *kYTServiceClient) Screen(ctx context.Context, in *ScreenRequest, opts ...grpc.CallOption) (*ScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenResponse)
	err := c.cc.Invoke(ctx, KYTService_Screen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kYTServiceClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, KYTService_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KYTServiceServer is the server API for KYTService service.
// All implementations must embed UnimplementedKYTServiceServer
// for forward compatibility.
//
// KYTService is served by the AML / KYT Screening service for the
// Transaction Orchestrator on the synchronous transaction path.
type KYTServiceServer interface {
	// Screen runs a synchronous KYT screen for a destination address.
	Screen(context.Context, *ScreenRequest) (*ScreenResponse, error)
	// GetAlert returns the alert with the given id (compliance dashboard).
	GetAlert(context.Context, *GetAlertRequest) (*Alert, error)
	mustEmbedUnimplementedKYTServiceServer()
}

// UnimplementedKYTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKYTServiceServer struct{}

func (UnimplementedKYTServiceServer) Screen(context.Context, *ScreenRequest) (*ScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screen not implemented")
}
func (UnimplementedKYTServiceServer) GetAlert(context.Context, *GetAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedKYTServiceServer) mustEmbedUnimplementedKYTServiceServer() {}
func (UnimplementedKYTServiceServer) testEmbeddedByValue()                    {}

// UnsafeKYTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KYTServiceServer will
// result in compilation errors.
type UnsafeKYTServiceServer interface {
	mustEmbedUnimplementedKYTServiceServer()
}

func RegisterKYTServiceServer(s grpc.ServiceRegistrar, srv KYTServiceServer) {
	// If the following call panics, it indicates UnimplementedKYTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KYTService_ServiceDesc, srv)
}

func _KYTService_Screen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYTServiceServer).Screen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYTService_Screen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYTServiceServer).Screen(ctx, req.(*ScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KYTService_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYTServiceServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYTService_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYTServiceServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KYTService_ServiceDesc is the grpc.ServiceDesc for KYTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KYTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyt.KYTService",
	HandlerType: (*KYTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screen",
			Handler:    _KYTService_Screen_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _KYTService_GetAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyt.proto",
}
